---
- name: Ensure Helm is installed
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add ingress-nginx Helm repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy ingress-nginx chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_nginx_chart_version }}"
    release_namespace: ingress-nginx
    create_namespace: true
    wait: true
    values:
      controller:
        service:
          type: LoadBalancer
